---
- name:           Set Locale for PHP PPA
  locale_gen:     name=en_US.UTF-8

- name:           Add PHP PPA
  apt_repository: repo='ppa:ondrej/php'

- name:           Install PHP
  apt:            name=php7.0
                  update_cache=yes

- name:           Install PHP Modules
  apt:            name={{ item }}
  with_items:
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-xml
    - php7.0-zip

- name:          Enable PHP Modules
  shell:         phpenmod {{ item }}
  with_items:
    - curl
    - json
    - opcache
    - mbstring
    - mcrypt
    - mysqli
    - mysqlnd
    - xml
    - zip
  notify:        Restart PHP-FPM

- name:          Download Composer Installer
  get_url:       url=https://getcomposer.org/installer
                 dest=/tmp/composer-setup.php
                 checksum='sha384:7228c001f88bee97506740ef0888240bd8a760b046ee16db8f4095c0d8d525f2367663f22a46b48d072c816e7fe19959'

- name:          Install Composer
  shell:         php /tmp/composer-setup.php --filename=composer --install-dir=/usr/local/bin
                 rm /tmp/composer-setup.php
                 creates=/usr/local/bin/composer

- name:          Install Prestissimo (to speed up Composer)
  command:       composer global require hirak/prestissimo
